### ISSUE TITLE
[experience] .editor_config is needed

### ISSUE THREAD

**Issue by BayuDC** [gifaldyazkaa/hoshiro#16]
imagine failing on lint action but dont fucking know how to format this thing

**Comment by BayuDC** [comment]
the prettier config in package.json is not working in my machine

**Comment by gifaldyazkaa** [comment]
I've tried to migrate the prettier configurations such as line spacing, tab width, etc. to .editorconfig, but it doesn't work at all.
Tried format-checking command using `$ bunx prettier --config .editorconfig -c .` and this prettier thing can't read the editorconfig file and failing with errors.

Because there's no any solutions, I will close this issue as not planned (won't fix, can't repro, duplicate, stale, etc.)
